Controllers/ClientController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;
using System.Security.Cryptography;
using System.Collections.Generic;
using WebMatrix.WebData;
using WebSite.Filters;
using WebSite.Helpers;
using WebSite.Models;
using WebSite.WebServiceReference;
using System.Text;
using System.Text.RegularExpressions;
using SendingEmailwithoutAttachment.Models;
using System.Globalization;

namespace WebSite.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class ClientController : Controller
    {
        private static readonly UsersContext bd = new UsersContext();

        public struct DairyDay
        {
            public DateTime date;
            public String[][] StrLesson;
            public String[][] Notes;
            public String[] hometaskLesson;
            public String klass;
            public String EmployeeId;

            public DairyDay(int WeekDay, DateTime InitDate, Int32 klassId, Int32 Employee)
            {
                klass = klassId.ToString();
                EmployeeId = Employee.ToString();
                var mrc = "";
                var hmt = "";
                hometaskLesson = new string[9];
                StrLesson = new string[9][];
                Notes = new string[5][];
                string WeekTextDay = "";
                switch(WeekDay)
                {
                    case 1: WeekTextDay = "Понедельник"; break;
                    case 2: WeekTextDay = "Вторник"; break;
                    case 3: WeekTextDay = "Среда"; break;
                    case 4: WeekTextDay = "Четверг"; break;
                    case 5: WeekTextDay = "Пятница"; break;
                    case 6: WeekTextDay = "Суббота"; break;
                }
                date = InitDate.AddDays(WeekDay-1);
                var Shedules = WebApiConfig2.WebClient.ПолучитьРасписание(klassId).ToList();
                var Hometask = WebApiConfig2.WebClient.ПолучитьДомашниеЗадания(date, klassId).ToList();
                var q = from t in Shedules
                        where t.ДеньНедели.Наименование == WeekTextDay
                        select new string[2] { t.Предмет.Наименование, t.Предмет.Код.ToString()}.ToArray();
                var less = q.ToArray();

                for (int i = 0; i <= 8; i++)
                    {
                    var Marc = WebApiConfig2.WebClient.ПолучитьОценкуУченикаПоПредметуЗаПериод(Employee, date, date.AddDays(1), klassId).ToList();

                    if (Marc.Count > 0)
                    {
                        mrc = Marc[0].Оценка;
                    }
                    else
                    {
                        mrc = "";
                    }


                    var reqHometask = less.Length > i ? less[i][0] : "";
                    var w = from a in Hometask
                            where a.Предмет.Наименование == reqHometask
                            select a.Задание;
                    hometaskLesson = w.ToArray();

                    if (hometaskLesson.Length > 0)
                    {
                        hmt = hometaskLesson[0];
                    }
                    else
                    {
                        hmt = "";
                    }

                    StrLesson[i] = new string[3]
                        {
                            less.Length > i ? less[i][0] : "",
                            hmt,
                            mrc
                        };
                    }
            }
        }

        public ActionResult DiaryClient(string current)
        {
            var now = new DateTime();
            if (Request.Params["date"] != null)
            {
                now = Convert.ToDateTime(Request.Params["date"]);
            }
            else
            {
                now = DateTime.Now;
            }
            
            int Nowday = (int)now.DayOfWeek;
            now = now.AddDays((Nowday*-1)+1);
            var model = new List<DairyDay>();
            if (Request.Params["klass"] != null) for (int i = 1; i <= 6; i++)
                model.Add(new DairyDay(i, now, Convert.ToInt32(Request.Params["klass"]), Convert.ToInt32(Request.Params["empId"])));
            return View(model);
        }


            public ActionResult Index(string current)
        {
            string error_str = "";

            int current_pupil = (current == null) ? 0 : Int32.Parse(current);

            var userDB = new UsersContext();
            var user = userDB.UserProfiles.Find(WebSecurity.CurrentUserId);
            
            if (user == null)
                return PartialView("Error");
            
            ViewBag.Client = user.fullname;
            int id = 0;
            bool x = Int32.TryParse(user.ClientID, out id);
            if (x == false)
            {   error_str += "Ошибка: Недопустимый идентификатор клиента."; }
            else
            {
                WebServiceReference2.ИнтернетПользователь profile = null;
                int client_id = 0;

                try
                {
                    profile = WebApiConfig2.WebClient.ПолучитьПрофильПользователя(id);
                }
                catch (System.ServiceModel.FaultException ex)
                {
                    error_str += ex.Message;
                    ViewBag.HomeTasks = null;

                    var DB = new DataContext();
                    var error = new Error();
                    string str = "ClientID: " + user.ClientID;
                    error.Command = "ПолучитьПрофильПользователя " + str;
                    error.Text = ex.Message;
                    error.Date = DateTime.Now;
                    DB.Errors.Add(error);
                    DB.SaveChanges();
                }

                if (profile != null)
                {
                    client_id = profile.Клиент.Код;

                    if (profile.Ученики != null)
                    {

                        ViewBag.Profile = profile;
                        ViewBag.Pupils = profile.Ученики.ToList();

                        WebServiceReference2.Ученик_Строка CurrentPupil = null;

                        if (current_pupil == 0)
                        {
                            CurrentPupil = profile.Ученики.ToList()[0];
                            current_pupil = CurrentPupil.Код;
                        }
                        else
                        {
                            try
                            {
                                CurrentPupil = WebApiConfig2.WebClient.ПолучитьПрофильУченика(current_pupil);
                            }
                            catch (System.ServiceModel.FaultException ex)
                            {
                                error_str += ex.Message;
                                ViewBag.Pupil = null;

                                var DB = new DataContext();
                                var error = new Error();
                                string str = "PupilID: " + current_pupil;
                                error.Command = "ПолучитьПрофильУченика " + str;
                                error.Text = ex.Message;
                                error.Date = DateTime.Now;
                                DB.Errors.Add(error);
                                DB.SaveChanges();
                            }
                        }

                        ViewBag.current_pupil = CurrentPupil;
                        ViewBag.current_pupil_id = CurrentPupil.Код;

                        //ViewBag.img_byte = WebApiConfig2.WebClient.ПолучитьФотоУченика(ViewBag.current_pupil.Код);

                        var Payments = new List<WebServiceReference2.Оплата_Строка>();

                        try
                        {
                            Payments = WebApiConfig2.WebClient.ПолучитьОплату(client_id).ToList();
                        }
                        catch (System.ServiceModel.FaultException ex)
                        {
                            error_str += ex.Message;
                            ViewBag.HomeTasks = null;

                            var DB = new DataContext();
                            var error = new Error();
                            string str = "ClientID: " + client_id;
                            error.Command = "ПолучитьОплату " + str;
                            error.Text = ex.Message;
                            error.Date = DateTime.Now;
                            DB.Errors.Add(error);
                            DB.SaveChanges();
                        }

                        if (Payments != null)
                        {
                            DateTime null_date = DateTime.ParseExact("01.01.0001", "dd.MM.yyyy", CultureInfo.InvariantCulture);
                            DateTime attend_date = null_date;
                            DateTime diary_date = null_date;
                            DateTime hometask_date = null_date;

                            foreach (var item in Payments)
                            {
                                if (item.Ученик.Код == current_pupil)
                                {

                                    if (item.Тариф.Наименование.IndexOf("СМС") != -1)
                                    {
                                        //int months = decimal.ToInt32(item.Сумма / item.Тариф.Стоимость);
                                        //DateTime date = item.Дата.AddMonths(months);
                                        if (item.ДатаОкончания.CompareTo(attend_date) > 0)
                                        { attend_date = item.ДатаОкончания; }
                                    }
                                    else
                                        if (item.Тариф.Наименование.IndexOf("Оценки") != -1)
                                        {
                                            if (item.ДатаОкончания.CompareTo(diary_date) > 0)

Controllers/PupilController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using WebSite.Filters;
using WebSite.WebServiceReference;

namespace WebSite.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class PupilController : Controller
    {
        //
        // GET: /Pupil/

        public ActionResult Index(/* int pupilID */)
        {
            /*
            var user = Session["user"] as WSUserProfile;
            if (user == null)
                return PartialView("Error");
            
            var pupil = user.Client.Pupils.FirstOrDefault(s => s.ID == pupilID);
            if (pupil == null)
                return PartialView("Error");
            
            //ViewBag.Client = client;
            //ViewBag.Pupil = pupil;
            Session["Pupil"] = pupil;

            var d = DateTime.Now;

            var model = new PupilControllerModel
                        {
                            Client = user.Client,
                            Pupil = pupil
                        };
            
            return View(model);
             */
            return View();
        }

        public ActionResult PupilPhoto()
        {
            var pupil = Session["Pupil"] as WSPupil;
            if (pupil == null)
                return null;

            return File(pupil.Image, "image/jpeg");
        }
    }

    public class PupilControllerModel
    {
        public WSClient Client { get; set; }
        public WSPupil Pupil { get; set; }
        //public List<WSTask> Tasks { get; set; }
    }
}

Views/Client/Activate.cshtml
@{
    ViewBag.Title = "Активация аккаунта";
}

<div class="container">	
    <div id="text_area">
	    <div class="block text-justify">
            <h3>ВНИМАНИЕ!</h3>
            <p>Для завершения регистрации Ваша учетная запись должна быть активирована.</p>
            @*Код активации придет в СМС на указанный Вами номер.*@
            @* @ViewBag.Code *@
	    </div>
        
        <div class="account-container">
            <div class="content clearfix">
                @using (Html.BeginForm("Activate", "Client", null, FormMethod.Post, new { @class = "form-horizontal", @id = "ActivateForm" })) 
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary()
                    @ViewBag.Error

                    <h1 class="text-center">Активация аккаунта</h1>
                    <hr />                                  
         			<div class="form-group">
						<h4>@Html.Label("Код активации:", new { @class = "control-label col-xs-5" })</h4>
					    <div class="col-xs-7">
					        @Html.TextBox("Code", "", new { @class = "form-control input-lg" })
                        </div>
					</div>                    
                    <div class="form-group">
			            <div class="col-xs-offset-5 col-xs-4">
				            <button type="submit" class="btn btn-default btn-lg">Активировать</button>
			            </div>
		            </div>            
                }
            </div>
        </div>
    </div>
</div>

Views/Client/Cart.cshtml
@{
    ViewBag.Title = "Корзина";
}
@*
@section head
{    
    @Scripts.Render("~/Content/js/sha1.js") 
}
*@
<div class="container-fluid">	
    <div class="row">
        <div class="col-xs-3" style="padding: 30px 10px">
            <img src="@Url.Content("~/Content/img/cart.gif")" />
        </div>
        <div id="text_area" class="col-xs-9">
	        <div class="block text-center">
		        <h3 style="margin-left: -250px">Заполните форму</h3>
		        <p style="margin-left: -250px">После этого Вы будете перенаправлены на страницу оплаты в системе электронных платежей WebPay.</p>

                 @using (Html.BeginForm("PaySubmit", "Client", null, FormMethod.Post, new { @class = "form-horizontal", @id = "CartForm" }))   
                        {                            
                            @Html.AntiForgeryToken()
						    @Html.ValidationSummary(true)
                            <div style="display:none">
         				        <div class="form-group">
							        @Html.Label("Email:", new { @class = "control-label col-xs-offset-1 col-xs-1" })
                                    <div class="col-xs-3">
							            @Html.TextBox("email", (string)ViewBag.Email, new { @class = "form-control" })
						            </div>
						        </div>
						        <div class="form-group">
							        @Html.Label("Телефон:", new { @class = "control-label col-xs-offset-1 col-xs-1" })
                                    <div class="col-xs-3">
                                        <div class="input-group">
                                            <div class="input-group-addon"> +375 </div>
                                            @Html.TextBox("phone", (string)ViewBag.Phone, new { @class = "form-control" })
						                </div>
                                    </div>
						        </div> 
                            </div>
                            <div id="row_0" class="form-group">
							    @Html.Label("Услуга:", new { @class = "control-label col-xs-offset-1 col-xs-1" })
                                <div class="col-xs-3">
                                    <select class="form-control" id="GoodsSelect_0" name="GoodsSelect_0" num="0">
							            @foreach (var item in ViewBag.GoodsList)
                                        {
                                            <option itemid="@item.ID" price="@item.Price">
                                                @item.Name
                                            </option>
                                        }
						            </select>
                                </div>
                                <input type="hidden" id="goods_id_0" name="goods_id" value="0"> 
						    </div>
						    <div class='form-group'>
                                <label class='control-label col-xs-3'>Количество месяцев:</label>
                                <div class='col-xs-2'>
                                    <input class='form-control' type='number' id='months_0' name='months' min='1' max='9' value='1'>
                                </div>
						    </div>
                                 
                            <div id="row_1">     </div>
                            <div id="row_2">     </div>
                            <div id="row_3">     </div>
                            <div id="row_4">     </div>
                            <div id="row_5">     </div>
                            <div id="row_6">     </div>
                            <div id="row_7">     </div>
                            <div id="row_8">     </div>
                                
						    <div class="form-group">
                                <div class="col-xs-offset-2 col-xs-2">
                                    <button type="button" class="form-control btn btn-default" onclick="AddGoodsRow()">Добавить услугу</button>
                                </div>
                            </div>
                     
                            <div class="form-group">
                                <label class="control-label col-xs-offset-1 col-xs-1">Итого:</label>
                                <div class="col-xs-2">
                                    <input type="text" id="total_price" name="total_price" class="form-control" readonly> 
                                </div>
							    <div class="col-xs-2">
								    <button type="submit" class="form-control btn btn-default">Оплатить</button>
							    </div>
						    </div>
                        }
	        </div>
        </div>
    </div>
</div>

<div style="padding-top: 100px"> </div>
<div style="padding: 20px 50px" align="center">
    <a href="http://webpay.by">
        <img src="@Url.Content("~/Content/img/webpay.gif")" style="height: 32px" />
        <img src="@Url.Content("~/Content/img/visa.gif")" style="height: 32px" /> 
        <img src="@Url.Content("~/Content/img/verified.gif")" style="height: 32px" /> 
        <img src="@Url.Content("~/Content/img/mastercard.gif")" style="height: 32px" /> 
        <img src="@Url.Content("~/Content/img/securecode.gif")" style="height: 32px" />
    </a> 
    <br> ООО «Айдисмарт», УНП 391326759
</div>


@section scripts
{
    <script>
        var rows = 1;

        function AddGoodsRow() {
            $("#row_" + rows).html(
                "<div class='form-group'> \
                    <label class='control-label col-xs-offset-1 col-xs-1' for=''>Услуга:</label> \
                    <div class='col-xs-3'> \
                    <select class='form-control' id='GoodsSelect_" + rows + "' name='GoodsSelect_" + rows + "' num='" + rows + "'> \
                        <option itemid='0' price='0'>  </option> \
                        <option itemid='1' price='20000'> СМС Начальный </option> \
                        <option itemid='2' price='30000'> СМС Базовый </option> \
                        <option itemid='4' price='50000'> Оценки Базовый </option> \
                        <option itemid='6' price='30000'> Д/З Базовый </option> \
                        <option itemid='7' price='60000'> Новая карта доступа </option> \
                        <option itemid='8' price='30000'> Восстановление карты </option> \
                        <option itemid='9' price='10000'> Новая наклейка </option> \
                    </select> </div> \
                    <input type='hidden' id='goods_id_" + rows + "' name='goods_id' value='0'> \
                    <div class='col-xs-2'> \
                        <button type='button' class='form-control btn btn-default' onclick='DelGoodsRow(" + rows + ")'>Убрать</button> \
                    </div> \
                </div> \
				<div class='form-group'> \
                    <label class='control-label col-xs-3'>Количество месяцев:</label> \
                    <div class='col-xs-2'> \
                        <input class='form-control' type='number' id='months_" + rows + "' name='months' min='1' max='9' value='1'> \
                    </div> \
				</div>  "
            );
            rows++;
        }

        function DelGoodsRow(row) {
            $("#row_" + row).html("");
            SetTotalPrice();
        }

        function SetTotalPrice() {
            var price = 0;
            for (i = 0; i < 8; i++) {
                var p = $('#GoodsSelect_' + i).find("option:selected").attr('price');
                var id = $('#GoodsSelect_' + i).find("option:selected").attr('itemid');
                var m = 1;
                if ( $.inArray(id,["7","8","9"]) == -1)
                { m = $('#months_' + i).val(); }
                if (typeof p !== "undefined" & typeof m !== "undefined")
                { price += parseInt(p*m); }
            }
            $("#total_price").val(price);
        }

        $('#CartForm').on('change', 'select', (function () {
            var x = $(this).find("option:selected").attr('itemid');
            var n = $(this).attr('num');
            $('#goods_id_'+n).val(x);
            SetTotalPrice();
        }));

        $('#CartForm').on('change', 'input', (function () {
            SetTotalPrice();
        }));

        $(document).ready(function () {
            $("#CartForm").validate({
                rules: {
                    email: { required: true, email: true },
                    phone: { required: true, digits: true, minlength: 9, maxlength: 9 },
                    months: { required: true, digits: true, maxlength: 1 },
                    GoodsSelect_0: "required"
                },
                messages: {
                    email: {
                        required: "Введите адрес электронной почты",
                        email: "Введите корректный адрес"
                    },
                    phone: {
                        required: "Введите свой телефон",
                        digits: "Вводите только цифры",
                        minlength: "Введите ровно 9 цифр",
                        maxlength: "Введите ровно 9 цифр"
                    },
                    months: {
                        required: "Введите количество месяцев",
                        digits: "Вводите только цифры",
                        maxlength: "Максимальное количество месяцев: 9"
                    },
                    GoodsSelect_0: "Выберите услугу"
                }
            });
        });

        @*
        function hashFunction() {
            var str = document.getElementById("seed").value + document.getElementById("store_id").value +
                document.getElementById("order_num").value + document.getElementById("test").value +
                document.getElementById("currency").value + document.getElementById("total_price").value +
                "2cVkxpYfcp";
            var hash = CryptoJS.SHA1(str);
            document.getElementById("signature").value = hash;

            var now = new Date();
            var time = now.getYear() + now.getMonth() + now.getDate() +
                now.getHours() + now.getMinutes() + now.getSeconds() + now.getMilliseconds();
            document.getElementById("order_num").value = "Order_" + time;
            document.getElementById("seed").value = time;
        }
        *@
    </script>
}

Views/Client/GetUnits.cshtml
@model WebSite.Models.SetChildModel

@Html.DropDownListFor(m => m.Unit_ID, new SelectList(ViewBag.Units, "Код", "Наименование"), new { @class = "form-control", @id = "UnitSel"})

Views/Client/PaySubmit.cshtml
@{
    ViewBag.Title = "Оплата";
}

@section head
{    
    @Scripts.Render("~/Content/js/sha1.js") 
}

@section banner
{
	<style>
		#banner {	height: 200px;	}
	</style>

   <div id="banner">   </div>
}

<div class="container">	
    <div id="text_area">
	    <div class="block text-center">
		    <h3>Выполняется перенаправление</h3>

            <form id="PaySubmitForm" name="PaySubmitForm" action = "https://secure.sandbox.webpay.by:8843" method="Post">

                <input type="hidden" name="*scart">  
                <input type="hidden" name="wsb_version" value="2">  
                <input type="hidden" name="wsb_language_id" value="russian">  
                <input type="hidden" name="wsb_storeid" value="249227470" >  
                <input type="hidden" name="wsb_store" value="ООО &quot;АйДиСмарт&quot;">
                <input type="hidden" name="wsb_test" value="@ViewBag.test">  
                <input type="hidden" name="wsb_currency_id" value="BYR"> 
                <input type="hidden" name="wsb_return_url" value="http://idsmart.by/Home/Success">  
                <input type="hidden" name="wsb_cancel_return_url" value="http://idsmart.by/Home/Cancel">  
                <input type="hidden" name="wsb_notify_url" value="http://idsmart.by/Home/Notify"> 
                 
                <input type="hidden" name="wsb_email" value="@ViewBag.email" >  
                <input type="hidden" name="wsb_phone" value="@ViewBag.phone" >
                <input type="hidden" name="wsb_order_num" value="@ViewBag.Order_id"> 
       
                @{int i = 0;}
				@foreach (var item in ViewBag.SelectedGoodsList)
                {
                    <input type="hidden" name="wsb_invoice_item_name[@i]" value="@item.Name"> 
                    <input type="hidden" name="wsb_invoice_item_price[@i]" value="@item.Price"> 
                    <input type="hidden" name="wsb_invoice_item_quantity[@i]" value="@item.Months">
                    i++;
                }
                        
                <input type="hidden" name="wsb_total" value="@ViewBag.total_price"> 
                <input type="hidden" name="wsb_seed" value="@ViewBag.seed">   
                <input type="hidden" name="wsb_signature" value="@ViewBag.signature">
                <input type="submit" value="Купить">
            </form>
            <script>
                document.getElementById("PaySubmitForm").submit();
            </script>
	    </div>
    </div>
</div>


@section scripts
{

}

Views/Client/SetChild.cshtml
@model WebSite.Models.SetChildModel

@{
    ViewBag.Title = "Добавить ребенка";
}

<div class="account-container">
    <div class="content clearfix">
        @using (Html.BeginForm("SetChild", "Client", null, FormMethod.Post, new { @class = "form-horizontal", @id = "SetChildForm" })) 
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary()

            <h2>Зарегистрировать ребенка</h2>
            <hr>
            @ViewBag.School
             if (!String.IsNullOrEmpty(ViewBag.Errors))
             {    @ViewBag.Errors    }
            
			<div class="form-group">
                @Html.LabelFor(m => m.School_ID, new { @class = "control-label col-xs-5" })
				<div class="col-xs-7">
                    @Html.DropDownListFor(m => m.School_ID, new SelectList(ViewBag.Schools, "Код", "Наименование"), new { @class = "form-control", @id = "SchoolSelect"})
				</div>
			</div>
			<div class="form-group">
                @Html.LabelFor(m => m.Unit_ID, new { @class = "control-label col-xs-5" })
				<div class="col-xs-7" id="UnitSelect">
                    @Html.DropDownListFor(m => m.Unit_ID,
                        new SelectList( new List<Object> { new { Код = "0" , Наименование = "1А класс" } }, "Код", "Наименование"),
                        new { @class = "form-control"})
				</div>
			</div>
            <div class="form-group">
                @Html.LabelFor(m => m.Fullname_1, new { @class = "control-label col-xs-5" })
                <div class="col-xs-7">
                    @Html.TextBoxFor(m => m.Fullname_1, new { @class = "form-control", @placeholder = "Фамилия"})
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Fullname_2, new { @class = "control-label col-xs-5" })
                <div class="col-xs-7">
                    @Html.TextBoxFor(m => m.Fullname_2, new { @class = "form-control", @placeholder = "Имя"})
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Fullname_3, new { @class = "control-label col-xs-5" })
                <div class="col-xs-7">
                    @Html.TextBoxFor(m => m.Fullname_3, new { @class = "form-control", @placeholder = "Отчество"})
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Card_ID, new { @class = "control-label col-xs-5" })
                <div class="col-xs-7">
                    @Html.TextBoxFor(m => m.Card_ID, new { @class = "form-control", @placeholder = "111.22222"})
                    <br> <img src="@Url.Content("~/Content/img/card.gif")" style="height: 128px" />
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-offset-1 col-xs-3">
                    @Html.ActionLink("Отмена", "Active_chk", "Account", new { ReturnUrl = "/Client/Index" }, new { @class="btn btn-default btn-lg", @role="button" })
                </div>
                
			    <div class="col-xs-offset-4 col-xs-4">
				    <button type="submit" class="btn btn-default btn-lg">Добавить</button>
			    </div>
		    </div>
            
        }
    </div>
</div>



@section Scripts {
    <script>
        $(document).ready(function () {
            $.ajax({
                'url': '/Client/GetUnits',
                'type': 'POST',
                'dataType': 'html',
                'data': { school: $('#SchoolSelect').val() },
                'success': function (data) {
                    $('#UnitSelect').html(data);
                }
            });

            $('#SchoolSelect').on('change', (function () {
                $.ajax({
                    'url': '/Client/GetUnits',
                    'type': 'POST',
                    'dataType': 'html',
                    'data': { school: $('#SchoolSelect').val() },
                    'success': function (data) {
                        $('#UnitSelect').html(data);
                    }
                });
            }));
        });
         
        @*
            $("#SetChildForm").validate({
                rules: {
                    email: { required: true, email: true },
                    phone: { required: true, digits: true, minlength: 9, maxlength: 9 },
                    GoodsSelect_0: "required"
                },
                messages: {
                    email: {
                        required: "Введите адрес электронной почты",
                        email: "Введите корректный адрес"
                    },
                    phone: {
                        required: "Введите свой телефон",
                        digits: "Вводите только цифры",
                        minlength: "Введите ровно 9 цифр",
                        maxlength: "Введите ровно 9 цифр"
                    },
                    GoodsSelect_0: "Выберите услугу"
                }
            });
        *@
    </script>
}
@*
<div class="form-group">
    @Html.LabelFor(m => m.School_ID, new { @class = "control-label col-xs-5" })
	<div class="col-xs-7">
        @Html.DropDownListFor(m => m.School_ID, new SelectList(
                new List<Object>{ 
                    new { value = "1" , text = "Гимназия №8"  },
                    new { value = "2" , text = "Гимназия №1" }
                },
                "ID", "Name"),
            new { @class = "form-control"})
	</div>
</div>
<div class="form-group">
    @Html.LabelFor(m => m.Class_Name, new { @class = "control-label col-xs-5" })
	<div class="col-xs-7">
        @Html.TextBoxFor(m => m.Class_Name, new { @class = "form-control", @placeholder = "1А"})
	</div>
</div>            
*@