Controllers/OperatorController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web.Mvc;
using System.Web.Security;
using WebMatrix.WebData;
using WebSite.Filters;
using WebSite.Models;
using Newtonsoft.Json;

namespace WebSite.Controllers
{
    [Authorize(Roles = "admins, managers, operator, teacher")]
    [InitializeSimpleMembership]
    public class OperatorController : Controller
    {
        //
        // GET: /Operator/
        public ActionResult Index()
        {
            var userDB = new UsersContext();
            var user = userDB.UserProfiles.Find(WebSecurity.CurrentUserId);

            if (user == null)
                return PartialView("Error");

            ViewBag.User = user.fullname;

            return View();
        }
            // GET: /Operator/Journal
            public ActionResult Journal(string school)
        {
            var Schools = WebApiConfig2.WebClient.ПолучитьШколы().ToList();

            if (Roles.IsUserInRole("teacher"))
            {
                var userDB = new UsersContext();
                var user = userDB.UserProfiles.Find(WebSecurity.CurrentUserId);
                /*
                for (int i = Schools.Count - 1; i >= 0; i--)
                {
                    if (Schools[i].Код != Int32.Parse(user.SchoolID))
                    { Schools.RemoveAt(i); }
                }
                */
                if (user.SchoolID != null && user.SchoolID != "")
                {
                    var separators = new string[] { " ", "," };
                    string[] UserSchools = user.SchoolID.Split(separators, StringSplitOptions.RemoveEmptyEntries);
                    if (UserSchools.Length > 0)
                    {
                        for (int i = Schools.Count - 1; i >= 0; i--)
                        {
                            if (UserSchools.Contains(Schools[i].Код.ToString()) == false)
                            { Schools.RemoveAt(i); }
                        }                    
                    }
                }
            }
            /*
            for (int i = Schools.Count - 1; i >= 0; i--)
            {
                // Отключить Гимназию №8 от журнала
                if (Schools[i].Код < 2)
                { Schools.RemoveAt(i); }
            }
            */
            ViewBag.SList = Schools;

            ViewBag.Klass = "";
            ViewBag.School = (school == null) ? "" : school;
            ViewBag.Flag = 0;

            return View();
        }

        // Post: /Operator/Journal
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Journal(string school, int unit_id, string klass, int subject, string quarter)
        {
            string error_str = "";

            var Schools = WebApiConfig2.WebClient.ПолучитьШколы().ToList();
            int school_id = 0;

            foreach (var item in Schools)
            {
                if (item.Наименование == school)
                { school_id = item.Код; }
            }

            var Quarters = new List<WebServiceReference2.Четверть_Строка>();

            try
            {
                Quarters = WebApiConfig2.WebClient.ПолучитьЧетверти(school_id).ToList();
            }
            catch (System.ServiceModel.FaultException ex)
            {
                error_str += ex.Message;
                ViewBag.Pupil = null;

                var DB = new DataContext();
                var error = new Error();
                string str = "SchoolID: " + school_id;
                error.Command = "ПолучитьЧетверти " + str;
                error.Text = ex.Message;
                error.Date = DateTime.Now;
                DB.Errors.Add(error);
                DB.SaveChanges();
            }
            /*
            List<Quarter> Quarters = null;
            if (school == "Гимназия N1" || school == "Гимназия N2")
            {
                Quarters = new List<Quarter>
                {
                    new Quarter {ID = 0, Name = "1й триместр", Date1 = "01.09.2015", Date2 = "30.11.2015" },
                    new Quarter {ID = 1, Name = "2й триместр", Date1 = "01.12.2015", Date2 = "29.02.2016" },
                    new Quarter {ID = 2, Name = "3й триместр", Date1 = "01.03.2016", Date2 = "30.05.2016" },
                };
            }
            else
            {
                Quarters = new List<Quarter>
                {
                    new Quarter {ID = 0, Name = "1-я четверть", Date1 = "01.09.2015", Date2 = "25.10.2015" },
                    new Quarter {ID = 1, Name = "2-я четверть", Date1 = "02.11.2015", Date2 = "27.12.2015" },
                    new Quarter {ID = 2, Name = "3-я четверть", Date1 = "11.01.2016", Date2 = "20.03.2016" },
                    new Quarter {ID = 3, Name = "4-я четверть", Date1 = "28.03.2016", Date2 = "31.05.2016" },
                };
            }
            */
            ViewBag.Quarter = Quarters;
            /*
            if (quarter == "")
            {
                if (DateTime.Now.CompareTo
                    (DateTime.ParseExact(Quarters[1].Date1, "dd.MM.yyyy", CultureInfo.InvariantCulture)) <= 0)
                { quarter = "0"; }
                else if (DateTime.Now.CompareTo
                    (DateTime.ParseExact(Quarters[2].Date1, "dd.MM.yyyy", CultureInfo.InvariantCulture)) <= 0)
                { quarter = "1"; }
                else if (Quarters.Count > 3)
                {
                    if (DateTime.Now.CompareTo(DateTime.ParseExact(Quarters[3].Date1, "dd.MM.yyyy", CultureInfo.InvariantCulture)) <= 0)
                    { quarter = "2"; }
                    else
                    { quarter = "3"; }
                }
                else
                { quarter = "2"; }
            }
            */
            int quarter_id = 0;
            List<DateTime> Days = new List<DateTime>();
            var Months = new List<Month>();

            if (Quarters.Count > 0)
            {
                if (quarter == null)
                {
                    if (DateTime.Now.CompareTo(Quarters[1].НачалоЧетверти) <= 0)
                    { quarter = "1"; }
                    else if (DateTime.Now.CompareTo(Quarters[2].НачалоЧетверти) <= 0)
                    { quarter = "2"; }
                    else if (Quarters.Count > 3)
                    {
                        if (DateTime.Now.CompareTo(Quarters[3].НачалоЧетверти) <= 0)
                        { quarter = "3"; }
                        else
                        { quarter = "4"; }
                    }
                    else
                    { quarter = "3"; }
                }

                quarter_id = Int32.Parse(quarter);
                ViewBag.QuarterSel = quarter;
                
                var BeginDay = Quarters[quarter_id - 1].НачалоЧетверти;
                var EndDay = Quarters[quarter_id - 1].КонецЧетверти;
                //var BeginDay = DateTime.ParseExact(Quarters[quarter_id].Date1, "dd.MM.yyyy", CultureInfo.InvariantCulture);
                //var EndDay = DateTime.ParseExact(Quarters[quarter_id].Date2, "dd.MM.yyyy", CultureInfo.InvariantCulture);
                var start_date = DateTime.Now.AddDays(7);

                for (int i = 333; i >= 0; i--)
                {
                    var sub = TimeSpan.FromDays(i);
                    DateTime day = start_date.Subtract(sub);
                    if (DateTime.Compare(day, BeginDay) >= 0 && day.DayOfWeek != DayOfWeek.Sunday && day.DayOfWeek != DayOfWeek.Saturday)   // заменить на проверку по расписанию
                    { Days.Add(day); }
                    if (DateTime.Compare(day, EndDay) >= 0)
                    { break; }
                }
            }
            else
            { error_str += "Список четвертей пустой. "; }

            var Subjects = new List<WebServiceReference2.Предмет_Строка>();
            try
            {
                Subjects = WebApiConfig2.WebClient.ПолучитьПредметыКласса(unit_id).ToList();
                Subjects.Sort((x, y) =>
                {
                    return x.Наименование.CompareTo(y.Наименование);
                });
                ViewBag.Subjects = Subjects;
                if (Subjects.Count == 0)
                { error_str += "Пустой список предметов. "; }
            }
            catch (System.ServiceModel.FaultException ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.Subjects = null;

                var DB = new DataContext();
                var error = new Error();
                string str = "unit_id: " + unit_id.ToString();
                error.Command = "ПолучитьПредметыКласса " + str;
                error.Text = ex.Message;
                error.Date = DateTime.Now;
                DB.Errors.Add(error);
                DB.SaveChanges();
            }

            var TimeTables = new List<WebServiceReference2.Расписание_Строка>();
            try
            {
                TimeTables = WebApiConfig2.WebClient.ПолучитьРасписание(unit_id).ToList();
                ViewBag.TT = TimeTables;
                if (TimeTables.Count == 0)
                { error_str += "Расписание пустое. "; }
            }
            catch (System.ServiceModel.FaultException ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.TimeTables = null;

                var DB = new DataContext();
                var error = new Error();
                string str = "unit_id: " + unit_id.ToString();
                error.Command = "ПолучитьРасписание " + str;
                error.Text = ex.Message;
                error.Date = DateTime.Now;
                DB.Errors.Add(error);
                DB.SaveChanges();
            }

            for (int i = Days.Count - 1; i >= 0; i--)
            {
                string day_str = WeekDay(Days[i]);
                int flag = 0;
                foreach (var item in TimeTables)

Views/Operator/Album.cshtml
@model List<WebSite.WebServiceReference.WSPay>
@{
    ViewBag.Title = "Альбом класса";
}

<div class="container">	
    <div id="text_area">
        <div class="block text-justify">
            <h3>Альбом класса</h3>
            <hr>
            @ViewBag.Error

            @if (ViewBag.Flag != 1)
            {
                using (Html.BeginForm("Album", "Operator", null, FormMethod.Post, new { @class = "form-horizontal", @id = "AlbumForm" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary()

                    <div class="form-group">
                        <label class="control-label col-xs-1">Школа:</label>
                        <div class="col-xs-3">
				            <select class="form-control" name="school" id="SchoolSelect">
					            @foreach (var item in ViewBag.SList)
                                {
						            <option itemid="@item.Код">@item.Наименование </option>
                                }
				            </select>
                        </div>
                    </div>
                
                    <input type="hidden" name="unit_id" id="unit_id"> 
                    <input type="hidden" name="klass" id="klass"> 
                    <div id="UnitSelect">       </div>
                    <br>
                }
            }
            @if (ViewBag.Flag == 1)
            {
                <style>
                    .flex-container {
                        display: -webkit-flex;
                        display: flex;
                        max-width: 98%;
                        justify-content: space-around;
                        align-items: baseline;
                        flex-wrap: wrap;
                        align-content: flex-start;
                    }
                    .flex-block {
                        margin: 10px;
                        margin-bottom: 30px;
                        max-width: 125px;
                    }
                    .flex-block img {
                        display: block;
                        margin-left: auto;
                        margin-right: auto;
                        width: 125px;
                        min-width:125px;
                        min-height:125px;
                        border:1px solid darkgray;
                    }
                </style>
                using (Html.BeginForm("Album", "Operator", null, FormMethod.Post, new { @class = "form-horizontal", @id = "AlbumForm" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary()
                
                    <div class="form-group">  
                        <label class="control-label col-xs-3"> @ViewBag.School,  @ViewBag.Klass</label>    
                        <div class="col-xs-2">
                            @Html.ActionLink("Выбрать класс", "Album", "Operator", new { school = ViewBag.School }, new { @class="btn btn-default", @role="button" })
                        </div>
                    </div>
                    
                    <input type="hidden" name="school" id="school" value="@ViewBag.School">  
                    <input type="hidden" name="unit_id" id="unit_id" value="@ViewBag.UnitID">    
                    <input type="hidden" name="klass" id="klass" value="@ViewBag.Klass">  
                    
                    <br>
                }
                if (ViewBag.Error == null)
                {
                    <div class="flex-container">
                        @foreach (var item in ViewBag.Pupils)
                        {
                            <div class="flex-block">
                                <img alt="Нет фото" src="@Url.Content("~/Images/Pupils/" + item.Код + ".jpg")" />
                                <p style="text-align:center">
                                    @item.Фамилия <br>
                                    @item.Имя <br>
                                    @item.Отчество <br>
                                    @if (item.ДеньРождения.ToString("dd.MM") == ViewBag.Today.ToString("dd.MM"))
                                    {
                                        <b style="color:green">@item.ДеньРождения.ToString("dd.MM.yyyy")</b>
                                    }
                                    else if (item.ДеньРождения.ToString("dd.MM") == ViewBag.Tomorrow.ToString("dd.MM"))
                                    {
                                        <b style="color:orange">@item.ДеньРождения.ToString("dd.MM.yyyy")</b>
                                    }
                                    else if (item.ДеньРождения.ToString("dd.MM") == ViewBag.Tomorrow2.ToString("dd.MM"))
                                    {
                                        <b style="color:red">@item.ДеньРождения.ToString("dd.MM.yyyy")</b>
                                    }
                                    else
                                    {
                                        @item.ДеньРождения.ToString("dd.MM.yyyy")
                                    }
                                </p>
                            </div>
                        }
                    </div>
                    @*
                    <table class="table table-bordered">
                        <tbody> 
                                    <tr>  
                                        <td>
                                            
                                        </td>
                                    </tr>
                        </tbody>
                    </table>                
                    *@
                }
            }
        </div>
    </div>
</div>
<div style="padding: 50px"> </div>


@section scripts
{
    <script>
        $(document).ready(function () {
            if ('@ViewBag.School' != '')
            { $('#SchoolSelect').val('@ViewBag.School'); }

            $('#UnitSelect').on('click', '.klass_btn', (function () {
                var x = $(this).attr('itemid');
                $("#unit_id").val(x);
                var y = $(this).val();
                $("#klass").val(y);
            }));

            $.ajax({
                'url': '/Operator/GetUnitsGrid',
                'type': 'POST',
                'dataType': 'html',
                'data': { school: $('#SchoolSelect').find("option:selected").attr('itemid') },
                'success': function (data) {
                    $('#UnitSelect').html(data);
                }
            });            
        });

        $('#SchoolSelect').on('change', (function () {
            $.ajax({
                'url': '/Operator/GetUnitsGrid',
                'type': 'POST',
                'dataType': 'html',
                'data': { school: $('#SchoolSelect').find("option:selected").attr('itemid') },
                'success': function (data) {
                    $('#UnitSelect').html(data);
                }
            });
        }));

    </script>
}

Views/Operator/GetUnits.cshtml
@* @Html.DropDownListFor(m => m.Unit_ID, new SelectList(ViewBag.Units, "ID", "Name"), new { @class = "form-control", @id = "UnitSel"}) *@

<select class="form-control" name="unit_id" id="UnitSelect">
    @if(ViewBag.Whole == 1)
    {        
    <option value="0">Вся школа</option>
    }
	@foreach (var item in ViewBag.Units)
    {
		<option value="@item.Код" item_name="@item.Наименование">@item.Наименование</option>
    }
</select>

Views/Operator/GetUnitsGrid.cshtml
@*
@model WebSite.Models.SetChildModel
@Html.DropDownListFor(m => m.Unit_ID, new SelectList(ViewBag.Units, "ID", "Name"), new { @class = "form-control", @id = "UnitSel"})
*@
<table class="table classes">                    
    <tbody>
        @foreach (var parallel in ViewBag.Units)
        {
            <tr>
                @foreach (var unit in parallel)
                {
                    <td> <input type="submit" class="klass_btn btn btn-default" value="@unit.Наименование" itemid="@unit.Код" /> </td>
                }
            </tr>
        }
    </tbody>
</table>

Views/Operator/Hometask.cshtml
@model List<WebSite.WebServiceReference.WSPay>
@{
    ViewBag.Title = "Домашние задания";
}

<div class="container">	
    <div id="text_area">
        <div class="block text-justify">
            <h3>Домашние задания</h3>
            <hr>
            @ViewBag.Error

            @if (ViewBag.Flag != 1)
            {
                using (Html.BeginForm("Hometask", "Operator", null, FormMethod.Post, new { @class = "form-horizontal", @id = "HometaskForm" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary()

                    <div class="form-group">
                        <label class="control-label col-xs-1">Школа:</label>
                        <div class="col-xs-3">
				            <select class="form-control" name="school" id="SchoolSelect">
					            @foreach (var item in ViewBag.SList)
                                {
						            <option itemid="@item.Код">@item.Наименование </option>
                                }
				            </select>
                        </div>
                        <label class="control-label col-xs-1">Дата:</label>
                        <div class="col-xs-3">
                            <div class="input-group date" id="datepicker">
                                @Html.TextBox("date", (string)ViewBag.Date, new { @class = "form-control", @id = "DateSelect" })
                                <div class="input-group-addon"> <span class="glyphicon glyphicon-calendar"></span> </div>
                            </div>
                        </div>
                    </div>
                
                    <input type="hidden" name="unit_id" id="unit_id"> 
                    <input type="hidden" name="klass" id="klass"> 
                    <div id="UnitSelect">       </div>
                    <br>
                }
            }
            @if (ViewBag.Flag == 1)
            {
                using (Html.BeginForm("Hometask", "Operator", null, FormMethod.Post, new { @class = "form-horizontal", @id = "HometaskForm" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary()
                
                    <div class="form-group">                        
                        <label class="control-label col-xs-1">Дата:</label>
                        <div class="col-xs-3">
                            <div class="input-group date" id="datepicker">
                                @Html.TextBox("date", (string)ViewBag.Date.ToString("dd.MM.yyyy"), new { @class = "form-control" })
                                <div class="input-group-addon"> <span class="glyphicon glyphicon-calendar"></span> </div>
                            </div>
                        </div>    
                        <div class="col-xs-1">
                            <input type="submit" class="btn btn-default" value="Перейти" />
                        </div>
                        <label class="control-label col-xs-3"> @ViewBag.School,  @ViewBag.Klass</label>    
                        <div class="col-xs-2">
                            @Html.ActionLink("Выбрать класс", "Hometask", "Operator", new { school = ViewBag.School }, new { @class="btn btn-default", @role="button" })
                        </div>
                    </div>
                    
                    <input type="hidden" name="school" id="school" value="@ViewBag.School">  
                    <input type="hidden" name="unit_id" id="unit_id" value="@ViewBag.UnitID">    
                    <input type="hidden" name="klass" id="klass" value="@ViewBag.Klass">  
                    
                    <br>
                }
                if (ViewBag.Error == null)
                {
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th width="5%"> Урок</th>
                                <th width="25%"> Предмет </th>
                                <th> Домашнее задание </th>
                            </tr>
                        </thead>
                        <tbody> 
                                @{ int i = 1; }
                                @foreach (var item in ViewBag.Hometasks)
                                {
                                    <tr>  
                                        <td> @i </td>
                                        <td> @item.Предмет.Наименование @* = @item.Subject.ID *@ </td>
                                        <td class="editable" id="tasks" data-type="text" data-name="@ViewBag.UnitID" data-pk="@item.Предмет.Код" data-params="{date:'@ViewBag.Date'}" data-url="/Operator/EditHomeTask" data-onblur="submit" data-clear="false" data-showbuttons="false" data-toggle="click" data-emptytext="..."> @item.Задание </td>
                                    </tr>
                                    i++;
                                }
                        </tbody>
                    </table>                
                }
            }
        </div>
    </div>
</div>
<div style="padding: 50px"> </div>


@section scripts
{
    @Scripts.Render("~/Content/js/moment.js")    
    @Scripts.Render("~/Content/js/moment.ru.js")    
    @Scripts.Render("~/Content/js/bootstrap-datetimepicker.min.js") 
    <script>
        $(function () {
            $('#datepicker').datetimepicker({ pickTime: false });
        });

        $(document).ready(function () {
            if ('@ViewBag.School' != '')
            { $('#SchoolSelect').val('@ViewBag.School'); }
            $('#DateSelect').val(moment().format("DD.MM.YYYY"));

            $('#UnitSelect').on('click', '.klass_btn', (function () {
                var x = $(this).attr('itemid');
                $("#unit_id").val(x);
                var y = $(this).val();
                $("#klass").val(y);
            }));

            $.ajax({
                'url': '/Operator/GetUnitsGrid',
                'type': 'POST',
                'dataType': 'html',
                'data': { school: $('#SchoolSelect').find("option:selected").attr('itemid') },
                'success': function (data) {
                    $('#UnitSelect').html(data);
                }
            });
            
            $.validator.addMethod("IsDate", function (value, element) {
                return /^\d\d\.\d\d\.\d\d\d\d$/.test(value);
            }, "Введите дату в формате dd.mm.yyyy (например: 31.12.1999)");
            
            $("#HometaskForm").validate({
                rules: {
                    date: { required: true, IsDate: true }
                },
                messages: {
                    date: { required: "Введите дату" }
                }
            });
        });

        $('#SchoolSelect').on('change', (function () {
            $.ajax({
                'url': '/Operator/GetUnitsGrid',
                'type': 'POST',
                'dataType': 'html',
                'data': { school: $('#SchoolSelect').find("option:selected").attr('itemid') },
                'success': function (data) {
                    $('#UnitSelect').html(data);
                }
            });
        }));

    </script>
}

Views/Operator/Index.cshtml
@{
    ViewBag.Title = "Личный кабинет";
}

@section head
{
    @Styles.Render("~/Content/css/bootstrap-editable.css")
    @Scripts.Render("~/Content/js/bootstrap-editable.min.js")
}

<div class="container">
        <h3>@ViewBag.User</h3>
        <hr>

        <a class="btn btn-lg btn-success" role="button" href="/Operator/Journal"> Журнал </a>
        <a class="btn btn-lg btn-success" role="button" href="/Operator/Hometask"> Домашние задания </a>
        <a class="btn btn-lg btn-success" role="button" href="/Operator/Stats_absence_short"> Статистика </a>
        <a class="btn btn-lg btn-success" role="button" href="/Operator/Album"> Альбом </a>
        <a class="btn btn-lg btn-default disabled" role="button" href="/Operator/Sends"> Рассылка </a>
</div>


@section scripts
{

}