Controllers/PupilController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using WebSite.Filters;
using WebSite.WebServiceReference;

namespace WebSite.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class PupilController : Controller
    {
        //
        // GET: /Pupil/

        public ActionResult Index(/* int pupilID */)
        {
            /*
            var user = Session["user"] as WSUserProfile;
            if (user == null)
                return PartialView("Error");
            
            var pupil = user.Client.Pupils.FirstOrDefault(s => s.ID == pupilID);
            if (pupil == null)
                return PartialView("Error");
            
            //ViewBag.Client = client;
            //ViewBag.Pupil = pupil;
            Session["Pupil"] = pupil;

            var d = DateTime.Now;

            var model = new PupilControllerModel
                        {
                            Client = user.Client,
                            Pupil = pupil
                        };
            
            return View(model);
             */
            return View();
        }

        public ActionResult PupilPhoto()
        {
            var pupil = Session["Pupil"] as WSPupil;
            if (pupil == null)
                return null;

            return File(pupil.Image, "image/jpeg");
        }
    }

    public class PupilControllerModel
    {
        public WSClient Client { get; set; }
        public WSPupil Pupil { get; set; }
        //public List<WSTask> Tasks { get; set; }
    }
}

Controllers/UnitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebSite.Filters;
using WebSite.WebServiceReference;

namespace WebSite.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class UnitController : Controller
    {
        public ActionResult Index(int unitID)
        {
            var user = Session["user"] as WSUserProfile;
            WSUnit unit = null;

            if (user != null && user.Client != null)
            {
                var pupil = user.Client.Pupils.FirstOrDefault(s => s.Unit.ID == unitID);
                if (pupil != null)
                    unit = pupil.Unit;
            }
            else
            {
                if (user != null) unit = user.Pupil.Unit;
            }

            return View(unit);
        }
       
        public ActionResult Pupils(int id)
        {
            var pupils = WebApiConfig.WebClient.GetPupils(id);
            return PartialView(pupils);
        }

        public ActionResult Timetable(int id)
        {
            var list = WebApiConfig.WebClient.GetTimetables(id);
            return PartialView(list.GroupBy(s => s.Day.Name));
        }

        public ActionResult Journals(int id)
        {
            var list = WebApiConfig.WebClient.GetJournals(id);
            return PartialView(list);
        }

        public ActionResult Dnevnik(int id)
        {
            var list = WebApiConfig.WebClient.GetDnevnik(id, DateTime.Parse("20/03/2013"));
            return PartialView(list.GroupBy(s => s.Day.Name));
        }
       
    }
}

Views/Pupil/Index.cshtml
@model WebSite.Controllers.PupilControllerModel
@{
    ViewBag.Title = "Index";
}

@section head
{
    @Scripts.Render("~/Content/js/moment.min.js")
}
<div class="block">
@*
    <h3 class="block-title">@Model.Pupil.Name</h3>
    <table class="table table-hover table-bordered">
        <tbody>
            <tr>
                <td width="224" rowspan="3" valign="middle">
                    <img src="@Url.Action("PupilPhoto")" width="90%" height="100%" class="img-polaroid">
                </td>
                <td width="370" align="right" valign="middle">
                    <p><strong>Учебное заведение:</strong></p>
                </td>
                <td width="483" valign="middle">
                    <p>@Html.ActionLink(Model.Pupil.School.Name, "Details", "School", new { schoolID = Model.Pupil.School.ID }, null)</p>
                </td>
            </tr>
            <tr>
                <td align="right">
                    <p><strong>Класс:</strong></p>
                </td>
                <td valign="middle">
                    <p>@Html.ActionLink(Model.Pupil.Unit.Name, "Index", "Unit", new { unitID = Model.Pupil.Unit.ID }, null)</p>
                </td>
            </tr>
            <tr>
                <td align="right">
                    <p><strong>Руководитель:</strong></p>
                </td>
                <td valign="middle">
                    <p>@Html.ActionLink(Model.Pupil.Unit.Boss.Name, "Index", "Teacher", new { id = Model.Pupil.Unit.Boss.ID }, null)</p>
                </td>
            </tr>
        </tbody>
    </table>
    *@
    <hr />
    <div class="tabbable">
        <ul class="nav nav-tabs" id="pTab">
            <li>
                <a href="#tab1" data-toggle="tab">Дневник</a>
            </li>
            <li>
                <a href="#tab2" data-toggle="tab">Успеваемость</a>
            </li>
            <li>
                <a href="#tab3" data-toggle="tab">Расписание</a>
            </li>
            @if (Roles.IsUserInRole("managers") || Roles.IsUserInRole("admins"))
            {
                <li>
                    <a href="#tab4" data-toggle="tab">Фото</a>
                </li>
            }
        </ul>

        <div class="tab-content">
            <div class="tab-pane" id="tab1">
                <div>
                    <img src="@Url.Content("~/Content/img/loading.gif")"/>
                    <span>Loading ...</span>
                </div>
                <hr />
            </div>
            <div class="tab-pane" id="tab2">
                Успеваемость
            </div>
            <div class="tab-pane" id="tab3">
                <div>
                    <img src="@Url.Content("~/Content/img/loading.gif")"/>
                    <span>Loading ...</span>
                </div>
                <hr />
            </div>
            @if (Roles.IsUserInRole("managers") || Roles.IsUserInRole("admins"))
            {
                <div class="tab-pane" id="tab4">
                    <div>
                        <img src="@Url.Content("~/Content/img/loading.gif")"/>
                        <span>Loading ...</span>
                    </div>
                    <hr />
                </div>
            }
        </div>
    </div>
</div>
@*
@section scripts
{
    <script>
        var timetable = null;
        var dnevnik = null;

        $('a[data-toggle="tab"]').on('shown', function (e) {
            if (e.target.hash == '#tab1') {
                if (dnevnik == null) {
                    $(e.target.hash).load('/Unit/Dnevnik?id=@Model.Pupil.ID');
                    dnevnik = 1;
                }
            }
            if (e.target.hash == '#tab3') {
                if (timetable == null) {
                    $(e.target.hash).load('/Unit/Timetable?id=@Model.Pupil.Unit.ID');
                    timetable = 1;
                }
            }
        });
    </script>
}
*@