Controllers/ManagerController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web.Mvc;
using System.Web.Security;
using WebMatrix.WebData;
using WebSite.Filters;
using WebSite.Models;

namespace WebSite.Controllers
{
    [Authorize(Roles = "admins, managers")]
    [InitializeSimpleMembership]
    public class ManagerController : Controller
    {
        // GET: /Manager/
        public ActionResult Index()
        {
            var userDB = new UsersContext();
            var user = userDB.UserProfiles.Find(WebSecurity.CurrentUserId);

            if (user == null)
                return PartialView("Error");

            ViewBag.User = user.fullname;

            return View();
        }

        // Post: /Manager/Edit
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(string name, string pk, string value)
        {
            var DB = new DataContext();
            Text texts = DB.Texts.Where(p => p.Page == name).FirstOrDefault(e => e.Element == pk);
            texts.Value = value;
            DB.SaveChanges();

            return new HttpStatusCodeResult(200);
        }

        public ActionResult News_Add()
        {
            ViewBag.Message = "Добавить новость";

            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult News_Add(string title, string body, DateTime date)
        {
            var DB = new DataContext();
            News news = new News();
            news.Date = date;
            news.Title = title;
            news.Body = body;
            news.Active = 1;
            DB.News.Add(news);
            DB.SaveChanges();

            return RedirectPermanent("/Home/News");
        }

        public ActionResult News_Edit(int id)
        {
            ViewBag.Message = "Редактировать новость";

            var DB = new DataContext();
            ViewBag.News = DB.News.Find(id);            

            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult News_Edit(int id, string title, string body, DateTime date)
        {
            var DB = new DataContext();
            News news = DB.News.Find(id);
            news.Date = date; 
            news.Title = title;
            news.Body = body;
            DB.SaveChanges();

            return RedirectPermanent("/Home/News");
        }

        public ActionResult News_Hide(int id)
        {
            ViewBag.Message = "Удалить новость";

            var DB = new DataContext();
            ViewBag.News = DB.News.Find(id);  

            return View();
        }

        [HttpPost]
        public ActionResult News_Delete(int id)
        {
            var DB = new DataContext();
            News news = DB.News.Find(id); 
            news.Active = 0;
            DB.SaveChanges();

            return RedirectPermanent("/Home/News");
        }


        public ActionResult User_Add(string success)
        {
            ViewBag.Message = "Добавить клиента";
            //DateTime default_birthdate = DateTime.ParseExact("01.01.1990", "dd.MM.yyyy", CultureInfo.InvariantCulture);
            //ViewBag.Birthdate = default_birthdate;

            if (success != null)
            {
                if (success == "1")
                { ViewBag.Success = "Клиент добавлен успешно"; }
                else
                { ViewBag.Success = "Ошиба добавления клиента: " + success; }
            }

            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult User_Add(string username, string password, string client_id,
            string fullname1, string fullname2, string fullname3, string phone, string email, DateTime birthdate)
        {
            ViewBag.Message = "Добавить клиента";
            /*
            DateTime default_birthdate = DateTime.ParseExact("01.01.1990", "dd.MM.yyyy", CultureInfo.InvariantCulture);
            ViewBag.Birthdate = default_birthdate;
            
            var Schools = WebApiConfig2.WebClient.ПолучитьШколы().ToList();
            ViewBag.Schools = Schools;
            ViewBag.Date = model.Birthdate.ToString("dd.MM.yyyy");
            
            ViewBag.ParentSelect = new List<Object>
            { 
                new { value = "1" , text = "Родителем"  },
                new { value = "2" , text = "Педагогом" }
            };

            int parent = 1;
            TimeSpan ParentAge = new System.TimeSpan(20 * 365, 0, 0, 0);    // Минимальный возраст родителя - 20 лет
            if (birthdate < (DateTime.Now - ParentAge) && parent == 1 )
            {}
            */
            var regex1 = new Regex(@"^[а-яёА-ЯЁa-zA-Z0-9\-_]+$");
            var regex2 = new Regex(@"^[0-9]+$");
            var regex3 = new Regex(@"^[а-яёА-ЯЁ\-]+$");

            if (regex1.IsMatch(username) == true && username.Length > 2)
            {
                if (regex2.IsMatch(phone) == true && phone.Length == 9)
                {
                    if (regex3.IsMatch(fullname1) == true && fullname1.Length > 2)
                    {
                        if (regex3.IsMatch(fullname2) == true && fullname2.Length > 2)
                        {
                            if (regex3.IsMatch(fullname3) == true && fullname3.Length > 2)
                            {
                                if (password.Length > 4)
                                {
                                    if (birthdate < DateTime.Now)
                                    {
                                        // Попытка зарегистрировать пользователя
                                        try
                                        {
                                            WebSecurity.CreateUserAndAccount(username, password, new
                                            {
                                                Phone = "375" + phone,
                                                Email = email,
                                                Fullname_1 = fullname1,
                                                Fullname_2 = fullname2,
                                                Fullname_3 = fullname3,
                                                Birthdate = birthdate,
                                                Parent = 1,
                                                ClientID = client_id,
                                                Units = "",
                                                Active = 1,
                                                Code = 0
                                            });
                                            Roles.AddUserToRole(username, "users");
                                            Roles.AddUserToRole(username, "clients");

                                            return RedirectPermanent("/Manager/User_Add?success=1");
                                        }
                                        catch (MembershipCreateUserException e)
                                        {
                                            return RedirectPermanent("/Manager/User_Add?success=" + e.StatusCode.ToString());
                                        }
                                    }
                                    else { return RedirectPermanent("/Manager/User_Add?success=" + "bad_birtdate"); }
                                }
                                else { return RedirectPermanent("/Manager/User_Add?success=" + "bad_password"); }
                            }
                            else { return RedirectPermanent("/Manager/User_Add?success=" + "bad_fullname1"); }
                        }
                        else { return RedirectPermanent("/Manager/User_Add?success=" + "bad_fullname2"); }
                    }
                    else { return RedirectPermanent("/Manager/User_Add?success=" + "bad_fullname3"); }
                }
                else { return RedirectPermanent("/Manager/User_Add?success=" + "bad_phone"); }
            }
            else { return RedirectPermanent("/Manager/User_Add?success=" + "bad_username"); }

            // Появление этого сообщения означает наличие ошибки; повторное отображение формы
            //return View();
        }

        public ActionResult Login_stats()
        {
            ViewBag.Title = "Статистика входов на сайт";
            ViewBag.Flag = 0;

            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Login_stats(DateTime date1, DateTime date2)
        {
            ViewBag.Title = "Статистика входов на сайт";
            ViewBag.Date1 = date1.ToString("dd.MM.yyyy");
            ViewBag.Date2 = date2.ToString("dd.MM.yyyy");

            var DB = new DataContext();
            List<Login_log> logs = DB.Login_logs.ToList();
            List<Login_log> logs_current = new List<Login_log>();

            DateTime end_date = date2.AddDays(1).AddSeconds(-1);

            foreach (var log in logs)
            {
                if (log.log_date.CompareTo(date1) >= 0 && log.log_date.CompareTo(end_date) <= 0)
                {   logs_current.Add(log);  }
            }

            if (logs_current.Count < 1)
            {
                ViewBag.Error = "Нет результатов";
            }

            ViewBag.Logs = logs_current;
            ViewBag.Flag = 1;

            return View();
        }

    }
}

Views/Manager/Index.cshtml
@{
    ViewBag.Title = "Личный кабинет";
}

@section head
{
    @Styles.Render("~/Content/css/bootstrap-editable.css")
    @Scripts.Render("~/Content/js/bootstrap-editable.min.js")
}

<div class="container">
        <h3>@ViewBag.User</h3>
        <hr>
        @*
		<h4>
            <div class="col-xs-offset-1 col-xs-1"> @Html.ActionLink("Журнал", "Journal", "Manager") </div>
			<div class="col-xs-2"> @Html.ActionLink("Посещаемость 1", "Absence", "Manager") </div>
			<div class="col-xs-2"> @Html.ActionLink("Посещаемость 2", "Absence2", "Manager") </div>
			<div class="col-xs-2"> @Html.ActionLink("Посещаемость (сотрудники)", "Absence_stuff", "Manager") </div>
			<div class="col-xs-2"> @Html.ActionLink("Домашние задания", "Hometask", "Manager") </div>
		</h4>
        *@
        <p>
            <a class="btn btn-lg btn-success" role="button" href="/Operator/Journal"> Журнал </a>
            <a class="btn btn-lg btn-success" role="button" href="/Operator/Hometask"> Домашние задания </a>
            <a class="btn btn-lg btn-success" role="button" href="/Operator/Stats_absence_short"> Статистика</a>
            <a class="btn btn-lg btn-success" role="button" href="/Operator/Album"> Альбом </a>
            <a class="btn btn-lg btn-default disabled" role="button" href="/Operator/Sends"> Рассылка </a>
        </p>
        <p>
            <a class="btn btn-lg btn-success" role="button" href="/Manager/User_Add"> Добавить клиента </a>
            <a class="btn btn-lg btn-success" role="button" href="/Manager/Login_stats"> Статистика входов на сайт </a>
            @if (this.User.IsInRole("admins"))
            {   <a class="btn btn-lg btn-success" role="button" href="/Admin"> Управление пользователями </a>  }
        </p>
</div>


@section scripts
{

}

Views/Manager/Login_stats.cshtml
@*
@model List<WebSite.WebServiceReference.WSPay>
@{
    ViewBag.Title = "Статистика входов на сайт";
}
*@
<div class="container">	
    <div id="text_area">
        <div class="block text-justify">
            <h3>@ViewBag.Title</h3>
            <hr>

            @if (ViewBag.Flag != 1)
            {
                using (Html.BeginForm("Login_stats", "Manager", null, FormMethod.Post, new { @class = "form-horizontal", @id = "LoginLogsForm" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary()
                
                    <div class="form-group">
                        <label class="control-label col-xs-1">Дата С:</label>
                        <div class="col-xs-2">
                            <div class="input-group date" id="datepicker1">
                                @Html.TextBox("date1", (string)ViewBag.Date1, new { @class = "form-control", @id = "Date1Select" })
                                <div class="input-group-addon"> <span class="glyphicon glyphicon-calendar"></span> </div>
                            </div>
                        </div>
                    
                        <label class="control-label col-xs-2">Дата по:</label>
                        <div class="col-xs-2">
                            <div class="input-group date" id="datepicker2">
                                @Html.TextBox("date2", (string)ViewBag.Date2, new { @class = "form-control", @id = "Date2Select" })
                                <div class="input-group-addon"> <span class="glyphicon glyphicon-calendar"></span> </div>
                            </div>
                        </div>
                        
                        <div class="col-xs-2">
                            <input type="submit" class="btn btn-primary" value="Сформировать отчет" />
                        </div>
                    </div>                
                }
                <br>
            }
            @if (ViewBag.Flag == 1)
            {
                using (Html.BeginForm("Login_stats", "Manager", null, FormMethod.Post, new { @class = "form-horizontal", @id = "LoginLogsForm" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary()
                
                    <div class="form-group">
                        <label class="control-label col-xs-1">Дата С:</label>
                        <div class="col-xs-2">
                            <div class="input-group date" id="datepicker1">
                                @Html.TextBox("date1", (string)ViewBag.Date1, new { @class = "form-control", @id = "Date1Select" })
                                <div class="input-group-addon"> <span class="glyphicon glyphicon-calendar"></span> </div>
                            </div>
                        </div>
                    
                        <label class="control-label col-xs-2">Дата по:</label>
                        <div class="col-xs-2">
                            <div class="input-group date" id="datepicker2">
                                @Html.TextBox("date2", (string)ViewBag.Date2, new { @class = "form-control", @id = "Date2Select" })
                                <div class="input-group-addon"> <span class="glyphicon glyphicon-calendar"></span> </div>
                            </div>
                        </div>
                        
                        <div class="col-xs-2">
                            <input type="submit" class="btn btn-primary" value="Сформировать отчет" />
                        </div>
                        <div class="col-xs-2">
                            <input role="button" class="btn btn-default" id="printBtn" value="Распечатать" />
                        </div>
                    </div>                
                }
                <br>
                <h4> @ViewBag.Error </h4>
                
                if (ViewBag.Error == null)
                {
                    <div id="toPrint">
                        <h4 class="onlyPrint"> 
                            Статистика входов на сайт.
                            Дата с <span id="Date1Name"> </span> 
                            по <span id="Date2Name"> </span>
                        </h4>

                        <table id="ReportTable" class="table table-bordered tablesorter tableExport">
                            <thead>
                                <tr>
                                    <th>№</th>
                                    <th>Логин</th>
                                    <th>Дата</th>
                                </tr>
                            </thead>
                            <tbody>
                                    @foreach (var log in ViewBag.Logs)
                                    {
                                        <tr>  
                                            <td>@log.log_id</td>
                                            <td>@log.username</td>
                                            <td>@log.log_date</td>
                                        </tr>
                                    }
                            </tbody>
                        </table>   
                    </div>             
                }
            }
        </div>
    </div>
</div>
<div style="padding: 50px"> </div>


@section scripts
{
    @Scripts.Render("~/Content/js/moment.js")    
    @Scripts.Render("~/Content/js/moment.ru.js")    
    @Scripts.Render("~/Content/js/bootstrap-datetimepicker.min.js") 
    @Scripts.Render("~/Content/js/Blob.min.js")
    @Scripts.Render("~/Content/js/FileSaver.min.js") 
    @Scripts.Render("~/Content/js/xlsx.core.min.js")
    @Scripts.Render("~/Content/js/tableexport.min.js") 

    <script>
        $(function () {
            $('#datepicker1').datetimepicker({ pickTime: false });
            $('#datepicker2').datetimepicker({ pickTime: false });
        });

        $(document).ready(function () {
            $('#Date1Name').html('@ViewBag.Date1');
            $('#Date2Name').html('@ViewBag.Date2');

            $.validator.addMethod("IsDate", function (value, element) {
                return /^\d\d\.\d\d\.\d\d\d\d$/.test(value);
            }, "Введите дату в формате dd.mm.yyyy (например: 31.12.1999)");
            
            $("#HometaskForm").validate({
                rules: {
                    date1: { required: true, IsDate: true },
                    date2: { required: true, IsDate: true }
                },
                messages: {
                    date1: { required: "Введите дату" },
                    date1: { required: "Введите дату" }
                }
            });

            //$.fn.tableExport.charset = "charset=windows-1251";
            $.fn.tableExport.rowDel = "\r\n";

            $(".tableExport").tableExport({
                headings: true,                     // (Boolean), display table headings (th/td elements) in the <thead>
                footers: true,                      // (Boolean), display table footers (th/td elements) in the <tfoot>
                formats: ["xlsx", "xls", "csv", "txt"],     // (String[]), filetype(s) for the export
                fileName: "id",                     // (id, String), filename for the downloaded file
                bootstrap: true,                    // (Boolean), style buttons using bootstrap
                position: "bottom",                 // (top, bottom), position of the caption element relative to table
                ignoreRows: null,                   // (Number, Number[]), row indices to exclude from the exported file
                ignoreCols: null,                   // (Number, Number[]), column indices to exclude from the exported file
                ignoreCSS: ".noExport",             // (selector, selector[]), selector(s) to exclude cells from the exported file
                emptyCSS: ".emptyExport"            // (selector, selector[]), selector(s) to replace cells with an empty string in the exported file
            });

        });

    </script>
}

Views/Manager/News_Add.cshtml
@{
    ViewBag.Title = "Добавить новость";
}

@section banner
{
	<style>
		#banner {
			height: 200px;
			background: url(@Url.Content("~/Content/img/news.jpg")) center no-repeat;
		}
	</style>

   <div id="banner"> </div>
}

<div class="container">	
    <div id="text_area">
	    <div class="block text-center">
            <h3>Добавить новость</h3>
            <hr>            
            @using (Html.BeginForm("News_Add", "Manager", null, FormMethod.Post, new { @class = "form-horizontal", @id = "NewsAddForm" }))   
                {                            
                    @Html.AntiForgeryToken()
					@Html.ValidationSummary(true)
         			<div class="form-group">
                        <label class="control-label col-xs-2">Дата:</label>
                        <div class="col-xs-2">
                            <div class="input-group date" id="datepicker">
                                @Html.TextBox("date", "", new { @class = "form-control", @id = "DateSelect" })
                                <div class="input-group-addon"> <span class="glyphicon glyphicon-calendar"></span> </div>
                            </div>
                        </div>
                    </div>
         			<div class="form-group">
						@Html.Label("Заголовок:", new { @class = "control-label col-xs-2" })
                        <div class="col-xs-8">
							@Html.TextBox("title", "", new { @class = "form-control" })
						</div>
					</div>
					<div class="form-group">
						@Html.Label("Текст новости:", new { @class = "control-label col-xs-2" })
                        <div class="col-xs-8">
                            @Html.TextArea("body", "", new { @class = "form-control", rows = "5" })
                        </div>
					</div> 
                
                    <div class="form-group">
						<div class="col-xs-offset-5 col-xs-2">
							<button type="submit" class="form-control btn btn-default">Добавить</button>
						</div>
					</div>
                }                
	    </div>        
    </div>
</div>

<div style="padding-top:40px;"></div>

@section scripts
{
    @Scripts.Render("~/Content/js/moment.js")    
    @Scripts.Render("~/Content/js/moment.ru.js")    
    @Scripts.Render("~/Content/js/bootstrap-datetimepicker.min.js") 
    <script>
        $(function () {
            $('#datepicker').datetimepicker({ pickTime: false });
        });
        
        $(document).ready(function () {
            $('#DateSelect').val( moment().format("DD.MM.YYYY") );
        });

        /*
        var now = new Date();
        var date_str = [AddZero(now.getDate()), AddZero(now.getMonth() + 1), now.getFullYear()].join(".");
        function AddZero(num)
        { return (num >= 0 && num < 10) ? "0" + num : num + ""; }
        $('#DateSelect').val(date_str);
        */
    </script>
}

Views/Manager/News_Edit.cshtml
@{
    ViewBag.Title = "Редактировать новость";
}

@section banner
{
	<style>
		#banner {
			height: 200px;
			background: url(@Url.Content("~/Content/img/news.jpg")) center no-repeat;
		}
	</style>

   <div id="banner"> </div>
}

<div class="container">	
    <div id="text_area">
	    <div class="block text-center">
            <h3>Редактировать новость</h3>
            <hr>            
            @using (Html.BeginForm("News_Edit", "Manager", null, FormMethod.Post, new { @class = "form-horizontal", @id = "NewsEditForm" }))   
                {                            
                    @Html.AntiForgeryToken()
					@Html.ValidationSummary(true)
                
         			<div class="form-group">
                        <label class="control-label col-xs-2">Дата:</label>
                        <div class="col-xs-2">
                            <div class="input-group date" id="datepicker">
                                @Html.TextBox("date", (string)ViewBag.News.Date.ToString("dd.MM.yyyy"), new { @class = "form-control", @id = "DateSelect" })
                                <div class="input-group-addon"> <span class="glyphicon glyphicon-calendar"></span> </div>
                            </div>
                        </div>
                    </div>
         			<div class="form-group">
						@Html.Label("Заголовок:", new { @class = "control-label col-xs-2" })
                        <div class="col-xs-8">
							@Html.TextBox("title", (string)ViewBag.News.Title, new { @class = "form-control" })
						</div>
					</div>
					<div class="form-group">
						@Html.Label("Текст новости:", new { @class = "control-label col-xs-2" })
                        <div class="col-xs-8">
                            @Html.TextArea("body", (string)ViewBag.News.Body, new { @class = "form-control", rows = "5" })
                        </div>
					</div> 
                
                    <div class="form-group">
                        <input type="hidden" name="id" value="@ViewBag.News.ID"> 
						<div class="col-xs-offset-5 col-xs-2">
							<button type="submit" class="form-control btn btn-default">Сохранить</button>
						</div>
					</div>
                }                
	    </div>        
    </div>
</div>

<div style="padding-top:40px;"></div>

@section scripts
{
    @Scripts.Render("~/Content/js/moment.js")    
    @Scripts.Render("~/Content/js/moment.ru.js")    
    @Scripts.Render("~/Content/js/bootstrap-datetimepicker.min.js") 
    <script>
        $(function () {
            $('#datepicker').datetimepicker({ pickTime: false });
        });
    </script>
}

Views/Manager/News_Hide.cshtml
@{
    ViewBag.Title = "Удалить новость";
}

@section banner
{
	<style>
		#banner {
			height: 200px;
			background: url(@Url.Content("~/Content/img/news.jpg")) center no-repeat;
		}
	</style>

   <div id="banner"> </div>
}

<div class="container">	
    <div id="text_area">
	    <div class="block text-justify">           
            <h3>
                <small> @ViewBag.News.Date.ToString("dd.MM.yyyy") </small>
                <span style="padding-left: 20px"> @Html.Raw(ViewBag.News.Title) </span> 
            </h3> <hr>
            <p style="font-size: 18px"> @Html.Raw(ViewBag.News.Body) </p> <br>        
            @using (Html.BeginForm("News_Delete", "Manager", null, FormMethod.Post, new { @class = "form-horizontal", @id = "NewsHideForm" }))   
                {                            
                    @Html.AntiForgeryToken()
					@Html.ValidationSummary(true)                
                    <div class="form-group">
                        @Html.Label("Вы действительно хотите удалить эту новость?", new { @class = "control-label col-xs-5" })
                        <input type="hidden" name="id" value="@ViewBag.News.ID"> 
						<div class="col-xs-2">
							<button type="submit" class="form-control btn btn-default">Удалить</button>
						</div>
					</div>
                }                
	    </div>        
    </div>
</div>

<div style="padding-top:40px;"></div>

Views/Manager/User_Add.cshtml
@{
    ViewBag.Title = "Добавить клиента";
}
@*
@section banner
{
	<style>
		#banner {
			height: 200px;
			background: url(@Url.Content("~/Content/img/news.jpg")) center no-repeat;
		}
	</style>

   <div id="banner"> </div>
}
*@
<div class="container">	
    <div id="text_area">
	    <div class="block text-center">
            @if (ViewBag.Success != null)
            { 
                <h3>@ViewBag.Success</h3>
            }
            <h3>Добавить клиента</h3>
            <hr>            
            @using (Html.BeginForm("User_Add", "Manager", null, FormMethod.Post, new { @class = "form-horizontal", @id = "UserAddForm" }))   
                {                            
                    @Html.AntiForgeryToken()
					@Html.ValidationSummary(true)
                    
         			<div class="form-group">
						@Html.Label("Имя пользователя:", new { @class = "control-label col-xs-2" })
                        <div class="col-xs-8">
							@Html.TextBox("username", "", new { @class = "form-control" })
						</div>
					</div>
					<div class="form-group">
						@Html.Label("Пароль:", new { @class = "control-label col-xs-2" })
                        <div class="col-xs-8">
							@Html.TextBox("password", "", new { @class = "form-control" })
                        </div>
					</div> 
					<div class="form-group">
						@Html.Label("Фамилия:", new { @class = "control-label col-xs-2" })
                        <div class="col-xs-8">
							@Html.TextBox("fullname1", "Фамилия", new { @class = "form-control" })
                        </div>
					</div> 
					<div class="form-group">
						@Html.Label("Имя:", new { @class = "control-label col-xs-2" })
                        <div class="col-xs-8">
							@Html.TextBox("fullname2", "Имя", new { @class = "form-control" })
                        </div>
					</div> 
					<div class="form-group">
						@Html.Label("Отчество:", new { @class = "control-label col-xs-2" })
                        <div class="col-xs-8">
							@Html.TextBox("fullname3", "Отчество", new { @class = "form-control" })
                        </div>
					</div> 
         			<div class="form-group">
						@Html.Label("Идентификатор клиента:", new { @class = "control-label col-xs-2" })
                        <div class="col-xs-8">
							@Html.TextBox("client_id", "", new { @class = "form-control" })
						</div>
					</div>
                    <div class="form-group">
                        @Html.Label("Телефон:", new { @class = "control-label col-xs-2" })
                        <div class="col-xs-8">
                            <div class="input-group">
                                <div class="input-group-addon"> +375 </div>
                                @Html.TextBox("phone", "290000000", new { @class = "form-control"})
                            </div>
                        </div>
                    </div>
         			<div class="form-group">
						@Html.Label("E-mail:", new { @class = "control-label col-xs-2" })
                        <div class="col-xs-8">
							@Html.TextBox("email", "fake_mail@a.by", new { @class = "form-control" })
						</div>
					</div>
                    <div class="form-group">
                        <label class="control-label col-xs-2">Дата рождения:</label>
                        <div class="col-xs-2">
                            <div class="input-group date" id="datepicker">
                                @Html.TextBox("birthdate", "01.01.1900", new { @class = "form-control", @id = "birthdate" })
                                <div class="input-group-addon"> <span class="glyphicon glyphicon-calendar"></span> </div>
                            </div>
                        </div>
                    </div>
                
                    <div class="form-group">
						<div class="col-xs-offset-5 col-xs-2">
							<button type="submit" class="form-control btn btn-default">Добавить</button>
						</div>
					</div>
                }                
	    </div>        
    </div>
</div>

<div style="padding-top:40px;"></div>

@section scripts
{
    @Scripts.Render("~/Content/js/moment.js")    
    @Scripts.Render("~/Content/js/moment.ru.js")    
    @Scripts.Render("~/Content/js/bootstrap-datetimepicker.min.js") 
    <script>
        $(function () {
            $('#datepicker').datetimepicker({ pickTime: false });
        });
        
        $(document).ready(function () {
            //$('#DateSelect').val( moment().format("DD.MM.YYYY") );

            @*$('#birthdate').val('@ViewBag.Birthdate');*@

            $.validator.addMethod("IsDate", function (value, element) {
                return /^\d\d\.\d\d\.\d\d\d\d$/.test(value);
            }, "Введите дату в формате dd.mm.yyyy (например: 31.12.1999)");

        });

        /*
        var now = new Date();
        var date_str = [AddZero(now.getDate()), AddZero(now.getMonth() + 1), now.getFullYear()].join(".");
        function AddZero(num)
        { return (num >= 0 && num < 10) ? "0" + num : num + ""; }
        $('#DateSelect').val(date_str);
        */
    </script>
}